#!/usr/bin/env python

import os, sys

from musicpi_lcd.lcd         import LCD, buttons, colors
from musicpi_lcd.printer_sys import SystemPrinter
from musicpi_lcd.printer_mpd import MPDPrinter
from musicpi_lcd.printer_gps import GPSPrinter
from musicpi_lcd.loop        import Loop

def detach():
    stdin  = '/dev/null'
    stdout = '/dev/null'
    stderr = '/dev/null'
    
    try:
        pid = os.fork()
        if pid > 0:
            # exit first parent
            sys.exit(0)
    except OSError, e:
        sys.stderr.write("fork #1 failed: %d (%s)\n" % (e.errno, e.strerror))
        sys.exit(1)
        
    # decouple from parent environment
    os.chdir("/")
    os.setsid()
    os.umask(0)
    
    # do second fork
    try:
        pid = os.fork()
        if pid > 0:
            # exit from second parent
            sys.exit(0)
    except OSError, e:
        sys.stderr.write("fork #2 failed: %d (%s)\n" % (e.errno, e.strerror))
        sys.exit(1)
       
    # redirect standard file descriptors
    sys.stdout.flush()
    sys.stderr.flush()
    si = file(stdin, 'r')
    so = file(stdout, 'a+')
    se = file(stderr, 'a+', 0)
    os.dup2(si.fileno(), sys.stdin.fileno())
    os.dup2(so.fileno(), sys.stdout.fileno())
    os.dup2(se.fileno(), sys.stderr.fileno())

def checkIfRoot():
    if not os.geteuid() == 0:
        return False
    return True

def checkIfRunning(name, kill=False):
    pidfile = "/var/run/%s.pid" % name
    if not os.path.exists( pidfile):
        return False
    f = open(pidfile)
    oldpid = int(f.readline().strip())
    f.close()

    cmdlinefile = os.path.join('/proc',str(oldpid),'cmdline')
    if not os.path.exists( cmdlinefile):
        return False
    f = open(cmdlinefile)
    args = f.readline().strip().split('\0')
    f.close()
    if len(args) > 1 and not args[0].endswith(name):
        if not args[1].endswith(name):
            return False

    if kill:
        try:
            import signal, time
            os.kill(oldpid, signal.SIGTERM)
            time.sleep(1)
            os.kill(oldpid, signal.SIGKILL)
        except:
            pass
        return False
    
    return True
    
def createPIDFile(name):
    pidfile = '/var/run/%s.pid' % name 
    f = open(pidfile, 'w')
    print>>f, os.getpid()
    f.close()
    import atexit
    atexit.register(lambda: os.path.exists(pidfile) and os.remove(pidfile))

def main():
    name = 'musicpi-lcd'
    ticklength = 0.1
    cols = 16
    rows = 2
    
    import argparse
    parser = argparse.ArgumentParser(
        description=name)
    parser.add_argument( '-d', '--daemon',
                         help='run as daemon',         action="store_true")
    parser.add_argument( '-v', '--verbose',
                         help='enable verbose output', action="store_true")
    parser.add_argument( '-k', '--kill-running',
                         help='kill if running',       action="store_true")
    parser.add_argument( '-c', '--cols',       metavar='COLS', type=int,   default=cols,
                         help='number of columns (default: %(default)s)')
    parser.add_argument( '-r', '--rows',       metavar='ROWS', type=int,   default=rows,
                         help='number of rows (default: %(default)s)')
    parser.add_argument( '-t', '--timeout',    metavar='TICKS', type=int, default=round(15/ticklength) if 1 else 0,
                         help='display timeout in ticks, disable with 0 (default: %(default)s)')
    parser.add_argument( '-a', '--autochange', metavar='TICKS', type=int, default=0,
                         help='display cycle time in ticks, disable with 0 (default: %(default)s)')
    parser.add_argument( '-l', '--ticklength', metavar='SECS', type=float, default=ticklength,
                         help='display refresh time in seconds (default: %(default)s s)')
    cmdargs = parser.parse_args()

    if not checkIfRoot():
        print "Run as root"
        sys.exit(1)
        
    if checkIfRunning(name, kill=cmdargs.kill_running):
        print "Already running, exiting"
        sys.exit(0)

    if cmdargs.daemon: detach()
    createPIDFile(name)
    
    lcd = LCD()
    
    args = {
        'lcd':        lcd,
        'cols':       cmdargs.cols,
        'rows':       cmdargs.rows,
        'ticklength': cmdargs.ticklength,
        'autochange': cmdargs.autochange,
        'timeout':    cmdargs.timeout,
        'debug':      cmdargs.verbose
        }
    printers  = [
        SystemPrinter(color=colors['red'],   **args),
        MPDPrinter   (color=colors['green'], **args),
        GPSPrinter   (color=colors['blue'],  **args),
        ]

    def on_exit():
        for p in printers:
            if cmdargs.verbose: print "Stopping", type(p).__name__
            p.stop()
            if cmdargs.verbose: print "Stopped ", type(p).__name__
        lcd.off()
    
    import atexit
    atexit.register(on_exit)

    if cmdargs.verbose:
        for p in printers:
            print "Using", type(p).__name__
        print "Starting loop"
        
    loop = Loop(printers=printers, **args)
    try:
        while True:
            loop.iterate()
    except KeyboardInterrupt:
        pass

if __name__ == '__main__':
    main()
